"""Agrega relación reclamos a Cliente

Revision ID: 0761a22cbad5
Revises: 63b8c36705f7
Create Date: 2026-01-15 15:06:36.970687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0761a22cbad5'
down_revision = '63b8c36705f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamo_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reclamo_id', sa.Integer(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reclamo_id'], ['reclamos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reclamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('documento_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('documento_numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('documento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('responsable_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolucion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_estimada_resolucion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tipo_reclamo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('prioridad',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_reclamos_numero_reclamo'))
        batch_op.create_unique_constraint(None, ['numero'])
        batch_op.drop_constraint(batch_op.f('reclamos_venta_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reclamos_orden_servicio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reclamos_asignado_a_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['responsable_id'], ['id'])
        batch_op.drop_column('solucion')
        batch_op.drop_column('satisfaccion_cliente')
        batch_op.drop_column('venta_id')
        batch_op.drop_column('numero_reclamo')
        batch_op.drop_column('fecha_reclamo')
        batch_op.drop_column('asignado_a_id')
        batch_op.drop_column('orden_servicio_id')
        batch_op.drop_column('fecha_resolucion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_resolucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden_servicio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asignado_a_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_reclamo', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_reclamo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('satisfaccion_cliente', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('solucion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reclamos_asignado_a_id_fkey'), 'usuarios', ['asignado_a_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reclamos_orden_servicio_id_fkey'), 'ordenes_servicio', ['orden_servicio_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reclamos_venta_id_fkey'), 'ventas', ['venta_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_reclamos_numero_reclamo'), ['numero_reclamo'], unique=True)
        batch_op.alter_column('prioridad',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('tipo_reclamo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fecha_cierre')
        batch_op.drop_column('fecha_estimada_resolucion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('resolucion')
        batch_op.drop_column('responsable_id')
        batch_op.drop_column('documento_id')
        batch_op.drop_column('documento_numero')
        batch_op.drop_column('documento_tipo')
        batch_op.drop_column('numero')

    op.drop_table('reclamo_historial')
    # ### end Alembic commands ###
