"""Add esperado fields to arqueo

Revision ID: 537ac54dfa49
Revises: 9426d95a8066
Create Date: 2026-01-10 08:43:20.778137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537ac54dfa49'
down_revision = '9426d95a8066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aperturas_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_efectivo_esperado', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_tarjeta_esperado', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_transferencias_esperado', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_cheques_esperado', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aperturas_caja', schema=None) as batch_op:
        batch_op.drop_column('monto_cheques_esperado')
        batch_op.drop_column('monto_transferencias_esperado')
        batch_op.drop_column('monto_tarjeta_esperado')
        batch_op.drop_column('monto_efectivo_esperado')

    # ### end Alembic commands ###
