"""Add arqueo fields to AperturaCaja

Revision ID: 9426d95a8066
Revises: c20c9cd1446c
Create Date: 2026-01-10 08:41:00.583014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9426d95a8066'
down_revision = 'c20c9cd1446c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aperturas_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_efectivo_real', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_tarjeta_real', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_transferencias_real', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_cheques_real', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aperturas_caja', schema=None) as batch_op:
        batch_op.drop_column('monto_cheques_real')
        batch_op.drop_column('monto_transferencias_real')
        batch_op.drop_column('monto_tarjeta_real')
        batch_op.drop_column('monto_efectivo_real')

    # ### end Alembic commands ###
