"""Crear tabla notas_debito_detalle

Revision ID: 98fccbef7687
Revises: d83257bef8cf
Create Date: 2026-01-26 09:43:19.284581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fccbef7687'
down_revision = 'd83257bef8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_debito_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_debito_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nota_debito_id'], ['notas_debito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_nota_debito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_debito_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('forma_pago_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['formas_pago.id'], ),
    sa.ForeignKeyConstraint(['nota_debito_id'], ['notas_debito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_credito_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notas_credito_detalle_venta_detalle_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notas_credito_detalle_nota_credito_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'venta_detalles', ['venta_detalle_id'], ['id'])
        batch_op.create_foreign_key(None, 'notas_credito', ['nota_credito_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_credito_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notas_credito_detalle_nota_credito_id_fkey'), 'notas_credito', ['nota_credito_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('notas_credito_detalle_venta_detalle_id_fkey'), 'venta_detalles', ['venta_detalle_id'], ['id'], ondelete='CASCADE')

    op.drop_table('pagos_nota_debito')
    op.drop_table('notas_debito_detalle')
    # ### end Alembic commands ###
