"""Add simplified compras flow with PagoCompra and MovimientoCaja

Revision ID: c20c9cd1446c
Revises: 
Create Date: 2026-01-07 09:10:41.031263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20c9cd1446c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apertura_caja_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['aperturas_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('origen_pago', sa.String(length=50), nullable=False),
    sa.Column('apertura_caja_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_caja_id', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_paga_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['aperturas_caja.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['movimiento_caja_id'], ['movimientos_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_paga_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compra_detalles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actualizado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('concepto', sa.String(length=255), nullable=True))
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fecha_documento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('usuario_registra_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stock_actualizado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_registra_id'], ['id'])
        batch_op.drop_column('tipo_pago')
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('dias_credito')

    with op.batch_alter_table('cuentas_por_pagar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_adeudado', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('fecha_vencimiento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('monto_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('saldo_pendiente',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas_por_pagar', schema=None) as batch_op:
        batch_op.alter_column('saldo_pendiente',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('monto_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('fecha_vencimiento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('monto_adeudado')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_credito', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_pago', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('stock_actualizado')
        batch_op.drop_column('usuario_registra_id')
        batch_op.drop_column('fecha_documento')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('compra_detalles', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('concepto')
        batch_op.drop_column('stock_actualizado')

    op.drop_table('pagos_compra')
    op.drop_table('movimientos_caja')
    # ### end Alembic commands ###
